[tool.poetry]
name = "inteam-inc"
version = "0.1.0"
description = ""
authors = ["we1lman <andrey.velma2005@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
bcrypt = "^4.1.2"
python-dotenv = "^1.0.1"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
